dates:
  start: "2025-01-01"
  end: "2026-12-31"

domain:
  lat_min: 5.0
  lat_max: 30.0
  lon_min: 45.0
  lon_max: 105.0

resolution: 0.25

output_root: "data/raw"

# ============================================================
# COPERNICUS
# ============================================================

copernicus:

  # Sea surface temperature
  sst:
    enabled: true
    dataset_id: "METOFFICE-GLO-SST-L4-NRT-OBS-SST-V2"
    preferred_variables: 
      - "analyzed_sst"
    output_dir: "data/raw/sst"

  # Sea surface salinity
  sss:
    enabled: true
    dataset_id: "cmems_obs-mob_glo_phy-sss_nrt_multi_P1D"
    preferred_variables:
      - "sos"
    output_dir: "data/raw/sss"

  ssh:
    enabled: true
    dataset_id: "cmems_obs-sl_glo_phy-ssh_my_allsat-l4-duacs-0.125deg_P1D"
    preferred_variables:
      - "sla"
    output_dir: "data/raw/ssh"

  # Surface winds
  wind:
    enabled: true
    dataset_id: "cmems_obs-wind_glo_phy_nrt_l4_0.125deg_PT1H"
    preferred_variables:
      - "eastward_wind"
      - "northward_wind"
    output_dir: "data/raw/wind"

  # Surface currents
  currents:
    enabled: true
    dataset_id: "cmems_obs-mob_glo_phy-cur_nrt_0.25deg_P1D-m"
    preferred_variables:
      - "uo"
      - "vo"
    output_dir: "data/raw/currents"